window.stamps = [
            { id: 'POL-A1', text: 'OFABITI'},
            { id: 'POL-A2', text: '<O>FABITI'},
            { id: 'POL-A3', text: 'OFABITI'},
            { id: 'POL-A4', text: 'OFABIT'},
            { id: 'POL-A5', text: 'ABITIOF'},
            { id: 'POL-A6', text: '<A>BITVS.F<EC>'},
            { id: 'POL-A7', text: 'H.AB.ITVS'},
            { id: 'POL-A8', text: 'FABIII'},
            { id: 'POL-A9', text: 'OFIC.ACVTI'},
            { id: 'POL-A10', text: 'OFIC.ACVTI'},
            { id: 'POL-A11', text: 'OFIC.ACVTI' },
            { id: 'POL-A12', text: 'OF.ACVTI' },
            { id: 'POL-A13', text: 'OF.ACV' },
            { id: 'POL-A14', text: 'AC.BT.I:M' },
            { id: 'POL-A15', text: 'ACVTVS' },
            { id: 'POL-A16', text: 'ACTVS' },
            { id: 'POL-A17', text: 'ACVTV' },
            { id: 'POL-A18', text: 'ACVTV' },
            { id: 'POL-A19', text: 'ADIVTORF' },
            { id: 'POL-A20', text: 'OFIVLIAE[M]' },
            { id: 'POL-A21', text: 'AEMIL<I>' },
            { id: 'POL-A22', text: 'AEMILI' },
            { id: 'POL-A23', text: 'AGEDILVF' },
            { id: 'POL-A24', text: 'OFALBANI' },
            { id: 'POL-A25', text: 'OFALBANI' },
            { id: 'POL-A26', text: 'OFALBAN' },
            { id: 'POL-A27', text: 'C.VAL.ALBAN' },
            { id: 'POL-A28', text: 'GVAL.ALB' },
            { id: 'POL-A29', text: 'OF.ALBIN[I]' },
            { id: 'POL-A30', text: 'OF.ALBINI' },
            { id: 'POL-A31', text: 'OF.ALBIN' },
            { id: 'POL-A32', text: 'ALBINI' },
            { id: 'POL-A33', text: '[A]BLINI' },
            { id: 'POL-A34', text: 'ALBIN' },
            { id: 'POL-A35', text: 'CEX.AL[BINI]' },
            { id: 'POL-A36', text: 'OFALBI' },
            { id: 'POL-A37', text: 'ALBVS.FE' },
            { id: 'POL-A37*', text: 'ALIVS.FI' },
            { id: 'POL-A38', text: 'ALBVSFE' },
            { id: 'POL-A39', text: 'ALBI.FI' },
            { id: 'POL-A40', text: 'ALBVS' },
            { id: 'POL-A41', text: 'AL.BI' },
            { id: 'POL-A42', text: 'ALB' },
            { id: 'POL-A43', text: 'AM ANDIMA' },
            { id: 'POL-A44', text: 'AMANDI' },
            { id: 'POL-A45', text: 'AMARI' },
            { id: 'POL-A46', text: '[A]NE XTLAT' },
            { id: 'POL-A47', text: 'ANTEROSF' },
            { id: 'POL-A48', text: 'ANT EROS' },
            { id: 'POL-A49', text: 'OFAPRIS' },
            { id: 'POL-A50', text: 'OFAPRI' },
            { id: 'POL-A51', text: 'APRONIF' },
            { id: 'POL-A52', text: 'OFAPRO' },
            { id: 'POL-A53', text: 'OFAPRO' },
            { id: 'POL-A54', text: 'APTI' },
            { id: 'POL-A55', text: 'OF.AQVITANI' },
            { id: 'POL-A56', text: 'OFAQVITANI' },
            { id: 'POL-A56*', text: 'OFAQVITAN<I>' },
            { id: 'POL-B1', text: 'BALBVS.F'},
            { id: 'POL-B2', text: 'OFBA[SSINI]'},
            { id: 'POL-B3', text: 'OFBASSIN'},
            { id: 'POL-B4', text: 'OFBMSIN'},
            { id: 'POL-B5', text: 'OF.BASSI'},
            { id: 'POL-B6', text: 'OF.BASSI'},
            { id: 'POL-B7', text: 'OF.BASSI'},
            { id: 'POL-B8', text: 'OF.B[ASSI]'},
            { id: 'POL-B9', text: 'OF.BASSI'},
            { id: 'POL-B10', text: 'OFBASSI'},
            { id: 'POL-B11', text: 'OFBASSL'},
            { id: 'POL-B12', text: 'OFBASSI'},
            { id: 'POL-B13', text: 'OF[F]ASSI'},
            { id: 'POL-B14', text: 'OFBASSI'},
            { id: 'POL-B15', text: 'OFBASSI'},
            { id: 'POL-B16', text: 'OFBASI'},
            { id: 'POL-B17', text: 'OFBASI'},
            { id: 'POL-B18', text: 'OFBASI'},
            { id: 'POL-B19', text: 'OFBASS'},
            { id: 'POL-B20', text: 'OFBASS'},
            { id: 'POL-B21', text: 'OFBASS'},
            { id: 'POL-B22', text: 'OFBAS'},
            { id: 'POL-B23', text: 'OFBAS'},
            { id: 'POL-B24', text: 'BASSLOF'},
            { id: 'POL-B24*', text: 'BASSL<OF>'},
            { id: 'POL-B25', text: 'BASSIO'},
            { id: 'POL-B26', text: 'BASSIO'},
            { id: 'POL-B27', text: 'BASSVS'},
            { id: 'POL-B28', text: 'BASSVS'},
            { id: 'POL-B29', text: 'BASSI'},
            { id: 'POL-B30', text: 'BASSI'},
            { id: 'POL-B31', text: 'BASSI'},
            { id: 'POL-B32', text: 'BASSI'},
            { id: 'POL-B33', text: 'BASSI'},
            { id: 'POL-B34', text: 'BASSI'},
            { id: 'POL-B35', text: 'BASSI'},
            { id: 'POL-B36', text: 'BASSI'},
            { id: 'POL-B37', text: 'BASS[I]'},
            { id: 'POL-B38', text: 'BASSI'},
            { id: 'POL-B39', text: 'BSS[I]A' },
            { id: 'POL-B40', text: 'BASSI' },
            { id: 'POL-B41', text: 'BASSI' },
            { id: 'POL-B42', text: 'BASSI' },
            { id: 'POL-B43', text: 'BAS' },
            { id: 'POL-B44', text: 'BAS' },
            { id: 'POL-B45', text: 'OFBASSICOELI' },
            { id: 'POL-B46', text: 'OFBASSI.CO' },
            { id: 'POL-B47', text: 'OFBASSI.CO' },
            { id: 'POL-B48', text: 'OFBASSICO' },
            { id: 'POL-B49', text: 'OFBASSIC' },
            { id: 'POL-C10', text: 'ALVINI' },
            { id: 'POL-C11', text: 'AQVITANI' },
            { id: 'POL-C12', text: 'OFCAL' },
            { id: 'POL-C13', text: 'OFCALVI' },
            { id: 'POL-C14', text: 'OFCALVI' },
            { id: 'POL-C15', text: 'OFCALVI' },
            { id: 'POL-C16', text: 'OFCALVI' },
            { id: 'POL-C17', text: 'OFCALVI' },
            { id: 'POL-C18', text: 'OFCALVI' },
            { id: 'POL-C19', text: 'OFCALVI' },
            { id: 'POL-C20', text: 'OF'},
            { id: 'POL-C21', text: 'OFCALVI' },
            { id: 'POL-C38', text: 'OF'},  
            { id: 'POL-C41', text: 'OFCALV'},
            { id: 'POL-C42', text: 'FCALV'},
            { id: 'POL-C43', text: 'OFCAL'},
            { id: 'POL-C44', text: 'OFCAL'},
            { id: 'POL-C45', text: 'OFCAL'},
            { id: 'POL-C46', text: 'CALVI'},
            { id: 'POL-C47', text: 'CALVI'},
            { id: 'POL-C48', text: 'CALVI'},
            { id: 'POL-C49', text: 'CALVI'},
            { id: 'POL-C50', text: 'CAMI'},
            { id: 'POL-C51', text: 'OFIC.CANTI'},
            { id: 'POL-C52', text: 'OFICC.ANI'},
            { id: 'POL-C53', text: 'OFIC.CANITIJ'},
            { id: 'POL-C54', text: 'OFIC.CANT' },
            { id: 'POL-C55', text: 'OFI.CANTI.' },
            { id: 'POL-C56', text: 'OFI.CANTI' },
            { id: 'POL-C57', text: 'OFI.CANI' },
            { id: 'POL-C58', text: 'OFI.CANT' },
            { id: 'POL-C59', text: 'OFCANTI' },
            { id: 'POL-C60', text: 'CAPITOF' },
            { id: 'POL-C61', text: 'CAPIIO' },
            { id: 'POL-C62', text: 'CAPITOVA' },
            { id: 'POL-C63', text: 'OF.C.ARAN' },
            { id: 'POL-C64', text: 'CARANTIM' },
            { id: 'POL-C65', text: 'CA[RANT]F' },
            { id: 'POL-C66', text: 'CARBONISMA' },
            { id: 'POL-C67', text: 'CARBO' },
            { id: 'POL-C68', text: 'CARILLFE' },
            { id: 'POL-C70', text: 'CARVS.FE' },
            { id: 'POL-C71', text: 'CARVSF' },
            { id: 'POL-C72', text: 'OFCASTI' },
            { id: 'POL-C73', text: 'OFCAS[TI]' },
            { id: 'POL-C74', text: 'OFCASTI' },
            { id: 'POL-C75', text: 'OFCAST' },
            { id: 'POL-C76', text: 'OFCAST' },
            { id: 'POL-C77', text: 'OFCAS' },
            { id: 'POL-C78', text: 'OFCAS' },
            { id: 'POL-C79', text: 'CASTVS.FE' },
            { id: 'POL-C80', text: 'CASTV' },
            { id: 'POL-C81', text: 'CASSTI' },
            { id: 'POL-C81*', text: 'CASST<I>' },
            { id: 'POL-C82', text: '[F:C.]A.S' },
            { id: 'POL-C83', text: 'CASTI' },
            { id: 'POL-C84', text: 'CATLI.OFIC' },
            { id: 'POL-C85', text: 'OFCELADI>' },
            { id: 'POL-C86', text: 'OFCELADI' },
            { id: 'POL-C87', text: 'CELADVSF' },
            { id: 'POL-C88', text: 'CELAD.FE' },
            { id: 'POL-C89', text: 'CELADI.MAN' },
            { id: 'POL-C90', text: 'CELADIM' },
            { id: 'POL-C91', text: 'CIILADVS' },
            { id: 'POL-C92', text: 'CELAD' },
            { id: 'POL-C93', text: 'OF.C.EL.FISI' },
            { id: 'POL-C94', text: 'CEL[ERFEC]' },
            { id: 'POL-C95', text: 'CELEREE' },
            { id: 'POL-C96', text: 'CELE[ROS]' },
            { id: 'POL-C97', text: 'OFCICELRS' },
            { id: 'POL-C98', text: 'OF.CE[LSI]' },
            { id: 'POL-C99', text: 'OFCE' },
            { id: 'POL-C100', text: '[C]ELSIOF' },
            { id: 'POL-C101', text: 'CELSIO' },
            { id: 'POL-C102', text: 'CELSI[.F]' },
            { id: 'POL-C103', text: 'CELSI' },
            { id: 'POL-C104', text: 'OFCELSI' },
            { id: 'POL-C105', text: 'OFCELSI' },
            { id: 'POL-C106', text: 'CELACELSID' },
            { id: 'POL-C107', text: 'CEL[SI]' },
            { id: 'POL-C108', text: 'L.C.CEL.SI.OF' },
            { id: 'POL-C109', text: '[L.C.CELS]I:OF' },
            { id: 'POL-C110', text: 'L.C.C.ELSI.O' },
            { id: 'POL-C111', text: 'L.C.CELS[I]' },
            { id: 'POL-C112', text: 'OFC.N.CELSI' },
            { id: 'POL-C113', text: 'OF.C.N.CEL' },
            { id: 'POL-C114', text: 'OFC.N.CEL' },
            { id: 'POL-C115', text: '[C]ENN[A]TVS' },
            { id: 'POL-C116', text: 'CENNATI' }, 
            { id: 'POL-C117', text: 'OFCENSO' },
            { id: 'POL-C118', text: 'OFCENS' },
            { id: 'POL-C118*', text: 'OFCHNI&bsol;' },
            { id: 'POL-C119', text: 'OFCENS' },
            { id: 'POL-C120', text: 'OFC[E]NS' },
            { id: 'POL-C120*', text: 'OFCE<NS>' },
            { id: 'POL-C121', text: 'OFC.ENS' },
            { id: 'POL-C122', text: 'OF.C,EN' },
            { id: 'POL-C123', text: 'OF.CEN' },
            { id: 'POL-C123*', text: 'OF.CE<N>' },
            { id: 'POL-C124', text: 'OF.CEN' },
            { id: 'POL-C125', text: 'OFCEN' },
            { id: 'POL-C126', text: 'OFCEN' },
            { id: 'POL-C127', text: 'OFCIIN' },
            { id: 'POL-C128', text: 'CIIN.SO' },
            { id: 'POL-C129', text: 'CIRRATI' },
            { id: 'POL-C130', text: 'CITVR' }, 
            { id: 'POL-C131', text: 'G.IV[L.CLE.]' },
            { id: 'POL-C132', text: 'OFCOCI' },
            { id: 'POL-C133', text: 'OFCOCI' },
            { id: 'POL-C134', text: 'OFCOCI' },
            { id: 'POL-C135', text: 'COCIOF' },
            { id: 'POL-C136', text: 'COCVS' },
            { id: 'POL-C137', text: 'COCVS' },
            { id: 'POL-C138', text: 'COCVS' },
            { id: 'POL-C139', text: 'COCV' },
            { id: 'POL-C140', text: 'COCI' },
            { id: 'POL-C141', text: 'OFCOELI' },
            { id: 'POL-C142', text: 'C.OM' },
            { id: 'POL-C143', text: 'C.OM' },
            { id: 'POL-C144', text: 'CORII' },
            { id: 'POL-C145', text: 'COSOI' },
            { id: 'POL-C146', text: 'COSO' },
            { id: 'POL-C147', text: 'OFCOTTO' },
            { id: 'POL-C148', text: 'OFCOTOI' },
            { id: 'POL-C149', text: 'COTTOF' },
            { id: 'POL-C150', text: 'COTTO' },
            { id: 'POL-C151', text: 'COTTON' },
            { id: 'POL-C152', text: 'COTON' },
            { id: 'POL-C153', text: 'C.OTV' },
            { id: 'POL-C154', text: 'COTV' },
            { id: 'POL-C155', text: 'CRA' },
            { id: 'POL-C156', text: 'OF.CRESTIO' },
            { id: 'POL-C157', text: 'OFCRESTIO' },
            { id: 'POL-C158', text: 'OFCRSTIO' },
            { id: 'POL-C159', text: 'OF.C.RESTI' },
            { id: 'POL-C160', text: 'OFCRESTI' },
            { id: 'POL-C160*', text: '<O>FCREST<I>' },
            { id: 'POL-C161', text: 'OFCR[ESTI]' },
            { id: 'POL-C162', text: 'OFCRESTI' },
            { id: 'POL-C163', text: 'OFCREST' },
            { id: 'POL-C164', text: 'OFCRES<T>' },
            { id: 'POL-C165', text: 'OF.CRES' },
            { id: 'POL-C165*', text: 'OF.CRE<S>' },
            { id: 'POL-C166', text: 'OFC[RES]' },
            { id: 'POL-C167', text: 'OF.CRE' },
            { id: 'POL-C168', text: 'OFCRE' },
            { id: 'POL-C169', text: 'CRESTIO' },
            { id: 'POL-C170', text: 'CRESTI' },
            { id: 'POL-C171', text: 'CRESTI' },
            { id: 'POL-C172', text: '[C]REST[I]' },
            { id: 'POL-C173', text: 'CRIIS' },
            { id: 'POL-C174', text: 'CRICIROF' },
            { id: 'POL-C175', text: 'CRISPI.MA' },
            { id: 'POL-C175*', text: '<C>RISPI.MA' },
            { id: 'POL-C176', text: 'CRIS[PI]' },
            { id: 'POL-C177', text: 'CRISPVSX' },
            { id: 'POL-C178', text: 'CRVCVRO' },
            { id: 'POL-C179', text: 'CRVCVR' },
            { id: 'POL-C180', text: 'CRVCI' },
            { id: 'POL-D7', text: 'DAM'},  
            { id: 'POL-D8', text: 'DARIB[ITVS]'},  
            { id: 'POL-D9', text: 'DARIBITVS'},  
            { id: 'POL-D10', text: 'DARRAFEC'},
            { id: 'POL-D11', text: 'DARRA.FE'},
            { id: 'POL-D11*', text: 'DARRA.F<E>'},
            { id: 'POL-D12', text: 'DARRAFE'},
            { id: 'POL-D13', text: 'DARRAF'},
            { id: 'POL-D14', text: 'DARRA[---]'},
            { id: 'POL-D15', text: 'DIINTO'},
            { id: 'POL-D16', text: 'DIOCARI'},
            { id: 'POL-D17', text: '[DI]OGEN'},
            { id: 'POL-D18', text: 'DIORIF'},
            { id: 'POL-D19', text: 'DONATVS.FE'},
            { id: 'POL-D20', text: 'DONATVS.E'},
            { id: 'POL-D21', text: 'DONATS'},
            { id: 'POL-D22', text: 'DONTIOIIICI'},
            { id: 'POL-D23', text: 'DVBITATI'},
            { id: 'POL-E2', text: 'EPIDIVS'},
            { id: 'POL-F1', text: 'FABVS.FE'},
            { id: 'POL-F1*', text: '<F>ABVS<.>F<E>'},
            { id: 'POL-F2', text: 'OF.L.FABI[V]'},
            { id: 'POL-F3', text: 'FASTVS'},
            { id: 'POL-F4', text: 'FEDOTVSFE'},
            { id: 'POL-F5', text: 'FELLT[E]'},
            { id: 'POL-F6', text: 'FELICION[S]'},
            { id: 'POL-F7', text: 'FELICIT[---]'},
            { id: 'POL-F8', text: 'OFFELICIS'},
            { id: 'POL-F9', text: '<OF>FELIC<I>'},
            { id: 'POL-F10', text: 'OF.FELIC<I>'},
            { id: 'POL-F11', text: 'OFFELIC'},
            { id: 'POL-F12', text: 'FELICISD'},
            { id: 'POL-F13', text: '[FELIXS.F]EC.'},
            { id: 'POL-F14', text: 'FELIX.FEC'},
            { id: 'POL-F15', text: 'FELIXFIC' },
            { id: 'POL-F16', text: 'FELIXF' },
            { id: 'POL-F17', text: 'FELICIS.MAN' },
            { id: 'POL-F18', text: 'FELICISMAN' },
            { id: 'POL-F19', text: 'FELICISMA' },
            { id: 'POL-F20', text: 'FELICISM' },
            { id: 'POL-F21', text: 'FIILIX' },
            { id: 'POL-F22', text: 'FIILIX' },
            { id: 'POL-F23', text: 'FIILIX' },
            { id: 'POL-F24', text: 'FELICIS' },
            { id: 'POL-F25', text: 'FIILI.XSI' },
            { id: 'POL-F26', text: 'FELIXSEV' },
            { id: 'POL-F27', text: 'L.AC.FIC' },
            { id: 'POL-F28', text: 'OFI.FIRM' },
            { id: 'POL-F29', text: 'OF.FIRMO' },
            { id: 'POL-F30', text: 'OFFIRMO' },
            { id: 'POL-F31', text: 'OF.FI' },
            { id: 'POL-F32', text: 'OFIRM' },
            { id: 'POL-F33', text: 'FIRMO' },
            { id: 'POL-F34', text: 'FIRMO' },
            { id: 'POL-F35', text: 'FIRMO' },
            { id: 'POL-F36', text: 'O.FIRMONIS' },
            { id: 'POL-F36*', text: '<O.>FIRMONI<S>' },
            { id: 'POL-F37', text: 'FLORI[MAN]' },
            { id: 'POL-F38', text: 'FLORVS' },
            { id: 'POL-F39', text: 'FORMOSVS' },
            { id: 'POL-F40', text: '[OFF]RONTINI' },
            { id: 'POL-F41', text: 'OFFRONTINI' },
            { id: 'POL-F42', text: 'OFFR.NTNI' },
            { id: 'POL-F43', text: 'OFFRONTINI' },
            { id: 'POL-F44', text: 'OFFRONTIN' },
            { id: 'POL-F45', text: 'OFFRONTIN' },
            { id: 'POL-F46', text: 'O<F>FRON<II>' },
            { id: 'POL-F47', text: 'OFFRONII' },
            { id: 'POL-F48', text: '[O]FRONTI' },
            { id: 'POL-F49', text: 'OFFRON' },
            { id: 'POL-F50', text: 'OFRONTI' },
            { id: 'POL-F51', text: 'OFR.N' },
            { id: 'POL-F52', text: 'FRONTI' },
            { id: 'POL-F53', text: '[F]RON' },
            { id: 'POL-F54', text: 'FRONTOF' },
            { id: 'POL-F55', text: 'FRONTO' },
            { id: 'POL-F56', text: 'FVSCI' },
            { id: 'POL-F57', text: 'OFFVSCI' },
            { id: 'POL-F58', text: '[OF].FVSC' },
            { id: 'POL-F59', text: 'OF.FVS' },
            { id: 'POL-F60', text: 'FVSCI' },
            { id: 'POL-F61', text: 'FVSCI' },
            { id: 'POL-F62', text: 'FVSCI' },
            { id: 'POL-F63', text: 'F[VSC]I' },
            { id: 'POL-F64', text: 'FVSCI' },
            { id: 'POL-F65', text: 'FVSCI' },
            { id: 'POL-F66', text: 'FVSCI' },
            { id: 'POL-F67', text: 'FVS[CI]' },
            { id: 'POL-F68', text: 'FVSC' },
            { id: 'POL-F69', text: 'FVSC' },
            { id: 'POL-G1', text: 'GALBINIM' },
            { id: 'POL-G2', text: 'OFGALIC' },
            { id: 'POL-G3', text: '[G]ALLICANI.MA' },
            { id: 'POL-G4', text: 'GALLICA.MA' },
            { id: 'POL-G5', text: 'GALI[ICANI]' },
            { id: 'POL-G6', text: 'ALL[IC]AN' },
            { id: 'POL-G7', text: 'GALLI.MANVS' },
            { id: 'POL-G8', text: 'GALLIMA' },
            { id: 'POL-G9', text: 'GALLI' },
            { id: 'POL-G10', text: 'GEMINV' },
            { id: 'POL-G11', text: 'OFGEM.MAE' },
            { id: 'POL-G12', text: 'CLGEMMA' },
            { id: 'POL-G13', text: 'GEMAE' },
            { id: 'POL-G14', text: 'C.GEMM' },
            { id: 'POL-G15', text: 'GENALISF' },
            { id: 'POL-G16', text: '[O]FGERMA' },
            { id: 'POL-G17', text: '<GER>MANIOF' },
            { id: 'POL-G18', text: 'GERMANIOI' },
            { id: 'POL-G19', text: 'GERMANIOI' },
            { id: 'POL-G20', text: 'GERMNI<OF>' },
            { id: 'POL-G21', text: 'GERMANI.FI' },
            { id: 'POL-G22', text: '[GER]MANI<.F>' },
            { id: 'POL-G23', text: 'GERF' },
            { id: 'POL-G24', text: 'G.ERMANI' },
            { id: 'POL-G25', text: 'GERMANI' },
            { id: 'POL-G26', text: 'GERMA[NI]' },
            { id: 'POL-G27', text: 'GER[MNI]' },
            { id: 'POL-G28', text: 'CERMAIN' },
            { id: 'POL-G29', text: 'GERMANI' },
            { id: 'POL-G30', text: 'CERMAN' },
            { id: 'POL-G31', text: 'GERMA<N>' },
            { id: 'POL-G32', text: 'CERMAN' },
            { id: 'POL-G33', text: '[G]ERMAN' },
            { id: 'POL-G34', text: 'GERMA' },
            { id: 'POL-G35', text: 'GERMA' },
            { id: 'POL-G36', text: 'OIIGER' },
            { id: 'POL-G37', text: 'OFFLAVI.GER.' },
            { id: 'POL-G38', text: '<O>FFLAGER.' },
            { id: 'POL-G39', text: 'OF.FL.GER.' },
            { id: 'POL-G40', text: 'OFFL.CER' },
            { id: 'POL-G41', text: 'OFFLGER' },
            { id: 'POL-G42', text: 'OFFLGER' },
            { id: 'POL-G43', text: 'OF.F.GE[R.]' },
            { id: 'POL-G44', text: 'OFFGER' },
            { id: 'POL-G45', text: 'OFFCER' },
            { id: 'POL-G46', text: 'OFFGER.' },
            { id: 'POL-G47', text: 'OFFC.ER' },
            { id: 'POL-G48', text: 'OFFGER' },
            { id: 'POL-G49', text: 'OFFCER' },
            { id: 'POL-G50', text: 'OFFCEK' },
            { id: 'POL-G51', text: 'OFFCE' },
            { id: 'POL-H1', text: 'Q.IVL.HABI' },
            { id: 'POL-I1', text: '<O>FFIC.INGEN' },
            { id: 'POL-I2', text: 'OF.INGEN' },
            { id: 'POL-I3', text: 'OF.INGEN' },
            { id: 'POL-I4', text: 'OFINC.I' },
            { id: 'POL-I5', text: 'OFINC.I' },
            { id: 'POL-I6', text: 'OFINC' },
            { id: 'POL-I7', text: 'INGENVI.F' },
            { id: 'POL-I8', text: '[IN]GENVI' },
            { id: 'POL-I9', text: 'INGENVI' },
            { id: 'POL-I9*', text: '<I>NGEN<VI>' },
            { id: 'POL-I9**', text: '<I>NGE<NVI>' },
            { id: 'POL-I10', text: 'OFIVCVNDI' },
            { id: 'POL-I11', text: 'OFIVCVNDI' },
            { id: 'POL-I12', text: 'OF.[IV]CVN' },
            { id: 'POL-I13', text: 'OF.IVCVN' },
            { id: 'POL-I14', text: 'OF.IVCVN' },
            { id: 'POL-I15', text: 'OF.IVCVN' },
            { id: 'POL-I16', text: 'OF.IVCVN' },
            { id: 'POL-I17', text: 'IVCVNDVS' },
            { id: 'POL-I18', text: '[I]VCVNDV' },
            { id: 'POL-I19', text: 'IVCVND[I]' },
            { id: 'POL-I20', text: 'IVC.VND' },
            { id: 'POL-I21', text: '[I]VCVND' },
            { id: 'POL-I22', text: 'IVCVND' },
            { id: 'POL-I23', text: 'OFCO.IV<C>' },
            { id: 'POL-I24', text: 'OF.COIV' },
            { id: 'POL-I25', text: 'FCO.IV' },
            { id: 'POL-I26', text: 'ICOIV' },
            { id: 'POL-I27', text: 'SEX.IVL.IVCVND' },
            { id: 'POL-I28', text: 'OFIC.IVLI' },
            { id: 'POL-I29', text: ':OFIVI:' },
            { id: 'POL-I30', text: 'IVLI.' },
            { id: 'POL-I31', text: 'IVLLINI' },
            { id: 'POL-I32', text: 'IVLLINI' },
            { id: 'POL-I33', text: 'IVLLINI' },
            { id: 'POL-I34', text: 'IVLLIN' },
            { id: 'POL-I35', text: 'IVLLN' },
            { id: 'POL-I36', text: 'IVNII[I]' },
            { id: 'POL-I37', text: 'IVNII' },
            { id: 'POL-I38', text: 'I.VN' },
            { id: 'POL-I39', text: 'OFIVSTI' },
            { id: 'POL-I40', text: 'OFI.VST' },
            { id: 'POL-I41', text: 'OF.IVS.' },
            { id: 'POL-I42', text: 'IVSTI.OF' },
            { id: 'POL-I43', text: 'IVSTI.OF' },
            { id: 'POL-I44', text: 'IVSTID' },
            { id: 'POL-I45', text: 'IVSTI' },
            { id: 'POL-I46', text: '<I>VENALISMA' },
            { id: 'POL-L1', text: 'OF.LABIONIS' },
            { id: 'POL-L2', text: 'OF.L[ABIO]' },
            { id: 'POL-L3', text: 'OF.LABE' },
            { id: 'POL-L3*', text: 'OF.LAB<E>' },
            { id: 'POL-L3**', text: 'OF.LAB<E>' },
            { id: 'POL-L4', text: '=.LAB' },
            { id: 'POL-L5', text: 'LABIO' },
            { id: 'POL-L6', text: 'LARTIVS.' },
            { id: 'POL-L7', text: 'LAVRATVS' },
            { id: 'POL-L8', text: 'LAVR.I:O' },
            { id: 'POL-L9', text: 'LEGITVM.O' },
            { id: 'POL-L10', text: 'LENTVF' },
            { id: 'POL-L11', text: 'OFL.IIPI' },
            { id: 'POL-L12', text: 'LIBERTVS' },
            { id: 'POL-L13', text: '<L>IBERTVS' },
            { id: 'POL-L14', text: 'OFLICIN' },
            { id: 'POL-L15', text: 'OFLICN' },
            { id: 'POL-L16', text: 'LICINIANAO' },
            { id: 'POL-L17', text: 'LICINIANAO' },
            { id: 'POL-L18', text: '<L>IC.INIANA<O>' },
            { id: 'POL-L19', text: '<L>CNIANA<O>' },
            { id: 'POL-L20', text: 'LICINVS' },
            { id: 'POL-L21', text: 'L.ICN.VS' },
            { id: 'POL-L22', text: 'LIC.IA' },
            { id: 'POL-L23', text: 'LOGIRNM' },
            { id: 'POL-L24', text: 'LOCIRNVS' },
            { id: 'POL-L25', text: 'LOGIRNI' },
            { id: 'POL-L26', text: '<L>OGIRN' },
            { id: 'POL-L27', text: 'LORI.R' },
            { id: 'POL-L28', text: 'OF.LVCCEI' },
            { id: 'POL-L29', text: 'OF.LVCCEI' },
            { id: 'POL-L30', text: 'OFLVCCEI' },
            { id: 'POL-L31', text: 'OF.LVCCE' },
            { id: 'POL-L32', text: 'OF.LVCC' },
            { id: 'POL-L33', text: 'OF.LVCC' },
            { id: 'POL-L34', text: 'LVC[IVS]' },
            { id: 'POL-L34*', text: 'LVCIVS' },
            { id: 'POL-L35', text: 'LVPERCV.FE' },
            { id: 'POL-L36', text: 'LVPP[A.F]' },
            { id: 'POL-L37', text: 'LVPIMA' },
            { id: 'POL-L38', text: 'LVPVS' },
            { id: 'POL-M1', text: 'OFICMACCAR[I]' },
            { id: 'POL-M2', text: 'OFI.MACCA' },
            { id: 'POL-M3', text: 'OF.MACCAR' },
            { id: 'POL-M4', text: 'OF.MACC[AR]' },
            { id: 'POL-M4*', text: '<O>F.MACCA<R>' },
            { id: 'POL-M5', text: 'OF.MACCAR' },
            { id: 'POL-M7', text: 'OF.MACA' },
            { id: 'POL-M8', text: 'MACCARI' },
            { id: 'POL-M9', text: 'MACCARI' },
            { id: 'POL-M10', text: 'MACCA' },
            { id: 'POL-M11', text: 'MACA' },
            { id: 'POL-M12', text: 'MAC' },
            { id: 'POL-M13', text: 'MAC.RI.MAN' },
            { id: 'POL-M14', text: 'MA.AC.II.R' },
            { id: 'POL-M15', text: 'MAC[ER]' },
            { id: 'POL-M16', text: 'MACIR' },
            { id: 'POL-M17', text: 'MACRIN' },
            { id: 'POL-M18', text: 'MAG[N]IMA' },
            { id: 'POL-M19', text: 'MANDVILMA' },
            { id: 'POL-M20', text: 'MANDOF' },
            { id: 'POL-M21', text: '[MAN]DV.' },
            { id: 'POL-M22', text: 'OFMANSVE' },
            { id: 'POL-M23', text: 'OFMASV' },
            { id: 'POL-M24', text: 'MAPONI' },
            { id: 'POL-M25', text: 'MARINVS.FE' },
            { id: 'POL-M26', text: 'MARINI' },
            { id: 'POL-M27', text: 'MARINI' },
            { id: 'POL-M28', text: '[MA]RSI' },
            { id: 'POL-M29', text: 'MARS' },
            { id: 'POL-M30', text: 'MARS' },
            { id: 'POL-M31', text: 'MARTIA[LISFE]' },
            { id: 'POL-M32', text: 'MARTIALIS.VA' },
            { id: 'POL-M33', text: 'OFMASCLIN' },
            { id: 'POL-M34', text: 'MSCLINI' },
            { id: 'POL-M35', text: '[OF.]MASCLI' },
            { id: 'POL-M36', text: 'OFMASC[L]' },
            { id: 'POL-M37', text: 'OFMASO' },
            { id: 'POL-M38', text: 'OFMASCI' },
            { id: 'POL-M39', text: 'MASCLVS[.FE]' },
            { id: 'POL-M40', text: 'MASCVLVS' },
            { id: 'POL-M41', text: 'MASCLVS' },
            { id: 'POL-M42', text: 'MASCVL<I>' },
            { id: 'POL-M43', text: 'MASCLI' },
            { id: 'POL-M44', text: 'MASCLI' },
            { id: 'POL-M45', text: 'MASCL' },
            { id: 'POL-M46', text: 'MASCL' },
            { id: 'POL-M47', text: 'MASCLI.BAL BVS' },
            { id: 'POL-M48', text: 'OFMASC[VL]' },
            { id: 'POL-M49', text: 'OFMASCVL' },
            { id: 'POL-M50', text: 'OFMASCL' },
            { id: 'POL-M51', text: '<OF>MASCL' },
            { id: 'POL-M52', text: 'OFMASC.' },
            { id: 'POL-M53', text: 'OFMASC' },
            { id: 'POL-M54', text: 'OFMAS' },
            { id: 'POL-M55', text: 'OFMATE' },
            { id: 'POL-M56', text: 'OF.MAT.VGE' },
            { id: 'POL-M57', text: 'OFMATV' },
            { id: 'POL-M58', text: 'MEOILLVS' },
        ];
