window.stamps = [
            { id: 'A1', text: 'OFABITI'},
            { id: 'A2', text: '<O>FABITI'},
            { id: 'A3', text: 'OFABITI'},
            { id: 'A4', text: 'OFABIT'},
            { id: 'A5', text: 'ABITIOF'},
            { id: 'A6', text: '<A>BITVS.F<EC>'},
            { id: 'A7', text: 'H.AB.ITVS'},
            { id: 'A8', text: 'FABIII'},
            { id: 'A9', text: 'OFIC.ACVTI'},
            { id: 'A10', text: 'OFIC.ACVTI'},
            { id: 'A11', text: 'OFIC.ACVTI' },
            { id: 'A12', text: 'OF.ACVTI' },
            { id: 'A13', text: 'OF.ACV' },
            { id: 'A14', text: 'AC.BT.I:M' },
            { id: 'A15', text: 'ACVTVS' },
            { id: 'A16', text: 'ACTVS' },
            { id: 'A17', text: 'ACVTV' },
            { id: 'A18', text: 'ACVTV' },
            { id: 'A19', text: 'ADIVTORF' },
            { id: 'A20', text: 'OFIVLIAE[M]' },
            { id: 'A21', text: 'AEMIL<I>' },
            { id: 'A22', text: 'AEMILI' },
            { id: 'A23', text: 'AGEDILVF' },
            { id: 'A24', text: 'OFALBANI' },
            { id: 'A25', text: 'OFALBANI' },
            { id: 'A26', text: 'OFALBAN' },
            { id: 'A27', text: 'C.VAL.ALBAN' },
            { id: 'A28', text: 'GVAL.ALB' },
            { id: 'A29', text: 'OF.ALBIN[I]' },
            { id: 'A30', text: 'OF.ALBINI' },
            { id: 'A31', text: 'OF.ALBIN' },
            { id: 'A32', text: 'ALBINI' },
            { id: 'A33', text: '[A]BLINI' },
            { id: 'A34', text: 'ALBIN' },
            { id: 'A35', text: 'CEX.AL[BINI]' },
            { id: 'A36', text: 'OFALBI' },
            { id: 'A37', text: 'ALBVS.FE' },
            { id: 'A37*', text: 'ALIVS.FI' },
            { id: 'A38', text: 'ALBVSFE' },
            { id: 'A39', text: 'ALBI.FI' },
            { id: 'A40', text: 'ALBVS' },
            { id: 'A41', text: 'AL.BI' },
            { id: 'A42', text: 'ALB' },
            { id: 'A43', text: 'AM ANDIMA' },
            { id: 'A44', text: 'AMANDI' },
            { id: 'A45', text: 'AMARI' },
            { id: 'A46', text: '[A]NE XTLAT' },
            { id: 'A47', text: 'ANTEROSF' },
            { id: 'A48', text: 'ANT EROS' },
            { id: 'A49', text: 'OFAPRIS' },
            { id: 'A50', text: 'OFAPRI' },
            { id: 'A51', text: 'APRONIF' },
            { id: 'A52', text: 'OFAPRO' },
            { id: 'A53', text: 'OFAPRO' },
            { id: 'A54', text: 'APTI' },
            { id: 'A55', text: 'OF.AQVITANI' },
            { id: 'A56', text: 'OFAQVITANI' },
            { id: 'A56*', text: 'OFAQVITAN<I>' },
            { id: 'B1', text: 'BALBVS.F'},
            { id: 'B2', text: 'OFBA[SSINI]'},
            { id: 'B3', text: 'OFBASSIN'},
            { id: 'B4', text: 'OFBMSIN'},
            { id: 'B5', text: 'OF.BASSI'},
            { id: 'B6', text: 'OF.BASSI'},
            { id: 'B7', text: 'OF.BASSI'},
            { id: 'B8', text: 'OF.B[ASSI]'},
            { id: 'B9', text: 'OF.BASSI'},
            { id: 'B10', text: 'OFBASSI'},
            { id: 'B11', text: 'OFBASSL'},
            { id: 'B12', text: 'OFBASSI'},
            { id: 'B13', text: 'OF[F]ASSI'},
            { id: 'B14', text: 'OFBASSI'},
            { id: 'B15', text: 'OFBASSI'},
            { id: 'B16', text: 'OFBASI'},
            { id: 'B17', text: 'OFBASI'},
            { id: 'B18', text: 'OFBASI'},
            { id: 'B19', text: 'OFBASS'},
            { id: 'B20', text: 'OFBASS'},
            { id: 'B21', text: 'OFBASS'},
            { id: 'B22', text: 'OFBAS'},
            { id: 'B23', text: 'OFBAS'},
            { id: 'B24', text: 'BASSLOF'},
            { id: 'B24*', text: 'BASSL<OF>'},
            { id: 'B25', text: 'BASSIO'},
            { id: 'B26', text: 'BASSIO'},
            { id: 'B27', text: 'BASSVS'},
            { id: 'B28', text: 'BASSVS'},
            { id: 'B29', text: 'BASSI'},
            { id: 'B30', text: 'BASSI'},
            { id: 'B31', text: 'BASSI'},
            { id: 'B32', text: 'BASSI'},
            { id: 'B33', text: 'BASSI'},
            { id: 'B34', text: 'BASSI'},
            { id: 'B35', text: 'BASSI'},
            { id: 'B36', text: 'BASSI'},
            { id: 'B37', text: 'BASS[I]'},
            { id: 'B38', text: 'BASSI'},
            { id: 'B39', text: 'BSS[I]A' },
            { id: 'B40', text: 'BASSI' },
            { id: 'B41', text: 'BASSI' },
            { id: 'B42', text: 'BASSI' },
            { id: 'B43', text: 'BAS' },
            { id: 'B44', text: 'BAS' },
            { id: 'B45', text: 'OFBASSICOELI' },
            { id: 'B46', text: 'OFBASSI.CO' },
            { id: 'B47', text: 'OFBASSI.CO' },
            { id: 'B48', text: 'OFBASSICO' },
            { id: 'B49', text: 'OFBASSIC' },
            { id: 'C41', text: 'OFCALV'},
            { id: 'C42', text: 'FCALV'},
            { id: 'C43', text: 'OFCAL'},
            { id: 'C44', text: 'OFCAL'},
            { id: 'C45', text: 'OFCAL'},
            { id: 'C46', text: 'CALVI'},
            { id: 'C47', text: 'CALVI'},
            { id: 'C48', text: 'CALVI'},
            { id: 'C49', text: 'CALVI'},
            { id: 'C50', text: 'CAMI'},
            { id: 'C51', text: 'OFIC.CANTI'},
            { id: 'C52', text: 'OFICC.ANI'},
            { id: 'C53', text: 'OFIC.CANITIJ'},
            { id: 'C54', text: 'OFIC.CANT' },
            { id: 'C55', text: 'OFI.CANTI.' },
            { id: 'C56', text: 'OFI.CANTI' },
            { id: 'C57', text: 'OFI.CANI' },
            { id: 'C58', text: 'OFI.CANT' },
            { id: 'C59', text: 'OFCANTI' },
            { id: 'C60', text: 'CAPITOF' },
            { id: 'C61', text: 'CAPIIO' },
            { id: 'C62', text: 'CAPITOVA' },
            { id: 'C63', text: 'OF.C.ARAN' },
            { id: 'C64', text: 'CARANTIM' },
            { id: 'C65', text: 'CA[RANT]F' },
            { id: 'C66', text: 'CARBONISMA' },
            { id: 'C67', text: 'CARBO' },
            { id: 'C68', text: 'CARILLFE' },
            { id: 'C70', text: 'CARVS.FE' },
            { id: 'C71', text: 'CARVSF' },
            { id: 'C72', text: 'OFCASTI' },
            { id: 'C73', text: 'OFCAS[TI]' },
            { id: 'C74', text: 'OFCASTI' },
            { id: 'C75', text: 'OFCAST' },
            { id: 'C76', text: 'OFCAST' },
            { id: 'C77', text: 'OFCAS' },
            { id: 'C78', text: 'OFCAS' },
            { id: 'C79', text: 'CASTVS.FE' },
            { id: 'C80', text: 'CASTV' },
            { id: 'C81', text: 'CASSTI' },
            { id: 'C81*', text: 'CASST<I>' },
            { id: 'C82', text: '[F:C.]A.S' },
            { id: 'C83', text: 'CASTI' },
            { id: 'C84', text: 'CATLI.OFIC' },
            { id: 'C85', text: 'OFCELADI>' },
            { id: 'C86', text: 'OFCELADI' },
            { id: 'C87', text: 'CELADVSF' },
            { id: 'C88', text: 'CELAD.FE' },
            { id: 'C89', text: 'CELADI.MAN' },
            { id: 'C90', text: 'CELADIM' },
            { id: 'C91', text: 'CIILADVS' },
            { id: 'C92', text: 'CELAD' },
            { id: 'C93', text: 'OF.C.EL.FISI' },
            { id: 'C94', text: 'CEL[ERFEC]' },
            { id: 'C95', text: 'CELEREE' },
            { id: 'C96', text: 'CELE[ROS]' },
            { id: 'C97', text: 'OFCICELRS' },
            { id: 'C98', text: 'OF.CE[LSI]' },
            { id: 'C99', text: 'OFCE' },
            { id: 'C100', text: '[C]ELSIOF' },
            { id: 'C101', text: 'CELSIO' },
            { id: 'C102', text: 'CELSI[.F]' },
            { id: 'C103', text: 'CELSI' },
            { id: 'C104', text: 'OFCELSI' },
            { id: 'C105', text: 'OFCELSI' },
            { id: 'C106', text: 'CELACELSID' },
            { id: 'C107', text: 'CEL[SI]' },
            { id: 'C108', text: 'L.C.CEL.SI.OF' },
            { id: 'C109', text: '[L.C.CELS]I:OF' },
            { id: 'C110', text: 'L.C.C.ELSI.O' },
            { id: 'C111', text: 'L.C.CELS[I]' },
            { id: 'C112', text: 'OFC.N.CELSI' },
            { id: 'C113', text: 'OF.C.N.CEL' },
            { id: 'C114', text: 'OFC.N.CEL' },
            { id: 'C115', text: '[C]ENN[A]TVS' },
            { id: 'C116', text: 'CENNATI' }, 
            { id: 'C117', text: 'OFCENSO' },
            { id: 'C118', text: 'OFCENS' },
            { id: 'C118*', text: 'OFCHNI&bsol;' },
            { id: 'C119', text: 'OFCENS' },
            { id: 'C120', text: 'OFC[E]NS' },
            { id: 'C120*', text: 'OFCE<NS>' },
            { id: 'C121', text: 'OFC.ENS' },
            { id: 'C122', text: 'OF.C,EN' },
            { id: 'C123', text: 'OF.CEN' },
            { id: 'C123*', text: 'OF.CE<N>' },
            { id: 'C124', text: 'OF.CEN' },
            { id: 'C125', text: 'OFCEN' },
            { id: 'C126', text: 'OFCEN' },
            { id: 'C127', text: 'OFCIIN' },
            { id: 'C128', text: 'CIIN.SO' },
            { id: 'C129', text: 'CIRRATI' },
            { id: 'C130', text: 'CITVR' }, 
            { id: 'C131', text: 'G.IV[L.CLE.]' },
            { id: 'C132', text: 'OFCOCI' },
            { id: 'C133', text: 'OFCOCI' },
            { id: 'C134', text: 'OFCOCI' },
            { id: 'C135', text: 'COCIOF' },
            { id: 'C136', text: 'COCVS' },
            { id: 'C137', text: 'COCVS' },
            { id: 'C138', text: 'COCVS' },
            { id: 'C139', text: 'COCV' },
            { id: 'C140', text: 'COCI' },
            { id: 'C141', text: 'OFCOELI' },
            { id: 'C142', text: 'C.OM' },
            { id: 'C143', text: 'C.OM' },
            { id: 'C144', text: 'CORII' },
            { id: 'C145', text: 'COSOI' },
            { id: 'C146', text: 'COSO' },
            { id: 'C147', text: 'OFCOTTO' },
            { id: 'C148', text: 'OFCOTOI' },
            { id: 'C149', text: 'COTTOF' },
            { id: 'C150', text: 'COTTO' },
            { id: 'C151', text: 'COTTON' },
            { id: 'C152', text: 'COTON' },
            { id: 'C153', text: 'C.OTV' },
            { id: 'C154', text: 'COTV' },
            { id: 'C155', text: 'CRA' },
            { id: 'C156', text: 'OF.CRESTIO' },
            { id: 'C157', text: 'OFCRESTIO' },
            { id: 'C158', text: 'OFCRSTIO' },
            { id: 'C159', text: 'OF.C.RESTI' },
            { id: 'C160', text: 'OFCRESTI' },
            { id: 'C160*', text: '<O>FCREST<I>' },
            { id: 'C161', text: 'OFCR[ESTI]' },
            { id: 'C162', text: 'OFCRESTI' },
            { id: 'C163', text: 'OFCREST' },
            { id: 'C164', text: 'OFCRES<T>' },
            { id: 'C165', text: 'OF.CRES' },
            { id: 'C165*', text: 'OF.CRE<S>' },
            { id: 'C166', text: 'OFC[RES]' },
            { id: 'C167', text: 'OF.CRE' },
            { id: 'C168', text: 'OFCRE' },
            { id: 'C169', text: 'CRESTIO' },
            { id: 'C170', text: 'CRESTI' },
            { id: 'C171', text: 'CRESTI' },
            { id: 'C172', text: '[C]REST[I]' },
            { id: 'C173', text: 'CRIIS' },
            { id: 'C174', text: 'CRICIROF' },
            { id: 'C175', text: 'CRISPI.MA' },
            { id: 'C175*', text: '<C>RISPI.MA' },
            { id: 'C176', text: 'CRIS[PI]' },
            { id: 'C177', text: 'CRISPVSX' },
            { id: 'C178', text: 'CRVCVRO' },
            { id: 'C179', text: 'CRVCVR' },
            { id: 'C180', text: 'CRVCI' },
            { id: 'C10', text: 'ALVINI' },
            { id: 'C11', text: 'AQVITANI' },
            { id: 'C12', text: 'OFCAL' },
            { id: 'C13', text: 'OFCALVI' },
            { id: 'C14', text: 'OFCALVI' },
            { id: 'C15', text: 'OFCALVI' },
            { id: 'C16', text: 'OFCALVI' },
            { id: 'C17', text: 'OFCALVI' },
            { id: 'C18', text: 'OFCALVI' },
            { id: 'C19', text: 'OFCALVI' },
            { id: 'C20', text: 'OF'},
            { id: 'C21', text: 'OFCALVI' },
            { id: 'C38', text: 'OF'},  
            { id: 'D7', text: 'DAM'},  
            { id: 'D8', text: 'DARIB[ITVS]'},  
            { id: 'D9', text: 'DARIBITVS'},  
            { id: 'D10', text: 'DARRAFEC'},
            { id: 'D11', text: 'DARRA.FE'},
            { id: 'D11*', text: 'DARRA.F<E>'},
            { id: 'D12', text: 'DARRAFE'},
            { id: 'D13', text: 'DARRAF'},
            { id: 'D14', text: 'DARRA[---]'},
            { id: 'D15', text: 'DIINTO'},
            { id: 'D16', text: 'DIOCARI'},
            { id: 'D17', text: '[DI]OGEN'},
            { id: 'D18', text: 'DIORIF'},
            { id: 'D19', text: 'DONATVS.FE'},
            { id: 'D20', text: 'DONATVS.E'},
            { id: 'D21', text: 'DONATS'},
            { id: 'D22', text: 'DONTIOIIICI'},
            { id: 'D23', text: 'DVBITATI'},
            { id: 'E2', text: 'EPIDIVS'},
            { id: 'F1', text: 'FABVS.FE'},
            { id: 'F1*', text: '<F>ABVS<.>F<E>'},
            { id: 'F2', text: 'OF.L.FABI[V]'},
            { id: 'F3', text: 'FASTVS'},
            { id: 'F4', text: 'FEDOTVSFE'},
            { id: 'F5', text: 'FELLT[E]'},
            { id: 'F6', text: 'FELICION[S]'},
            { id: 'F7', text: 'FELICIT[---]'},
            { id: 'F8', text: 'OFFELICIS'},
            { id: 'F9', text: '<OF>FELIC<I>'},
            { id: 'F10', text: 'OF.FELIC<I>'},
            { id: 'F11', text: 'OFFELIC'},
            { id: 'F12', text: 'FELICISD'},
            { id: 'F13', text: '[FELIXS.F]EC.'},
            { id: 'F14', text: 'FELIX.FEC'},
            { id: 'G1', text: 'GALBINIM' },
            { id: 'G2', text: 'OFGALIC' },
            { id: 'G3', text: '[G]ALLICANI.MA' },
            { id: 'G4', text: 'GALLICA:MA' },
            { id: 'G5', text: 'GAL[ICANI]' },
            { id: 'G6', text: 'ALL[IC]AN' },
            { id: 'G7', text: 'GALLI.MANVS' },
            { id: 'G8', text: 'GALLIMA' },
            { id: 'G9', text: 'GALLI' },
            { id: 'G10', text: 'GEMINV' },
            { id: 'G11', text: 'OFGEM.MAE' },
            { id: 'G12', text: 'CLGEMMA' },
            { id: 'G13', text: 'GEMAE' },
            { id: 'G14', text: 'C.GEMM' },
            { id: 'G15', text: 'GENALISF' },
            { id: 'G16', text: '[O]FGERMA' },
            { id: 'G17', text: '<GER>MANIOF' },
            { id: 'G18', text: 'GERMANIOI' },
            { id: 'G19', text: 'GERMANIOI' },
            { id: 'G20', text: 'GERMINI<OF>' },
            { id: 'G21', text: 'GERMANI.FI' },
            { id: 'F15', text: 'FELIXFIC' },
            { id: 'F16', text: 'FELIXF' },
            { id: 'F17', text: 'FELICIS.MAN' },
            { id: 'F18', text: 'FELICISMAN' },
            { id: 'F19', text: 'FELICISMA' },
            { id: 'F20', text: 'FELICISM' },
            { id: 'F21', text: 'FIILIX' },
            { id: 'F22', text: 'FIILIX' },
            { id: 'F23', text: 'FIILIX' },
            { id: 'F24', text: 'FELICIS' },
            { id: 'F25', text: 'FIILI.XSI' },
            { id: 'F26', text: 'FELIXSEV' },
            { id: 'F27', text: 'L.AC.FIC' },
            { id: 'F28', text: 'OFI.FIRM' },
            { id: 'F29', text: 'OF.FIRMO' },
            { id: 'F30', text: 'OFFIRMO' },
            { id: 'F31', text: 'OF.FI' },
            { id: 'F32', text: 'OFIRM' },
            { id: 'F33', text: 'FIRMO' },
            { id: 'F34', text: 'FIRMO' },
            { id: 'F35', text: 'FIRMO' },
            { id: 'F36', text: 'O.FIRMONIS' },
            { id: 'F36*', text: '<O.>FIRMONI<S>' },
            { id: 'F37', text: 'FLORI[MAN]' },
            { id: 'F38', text: 'FLORVS' },
            { id: 'F39', text: 'FORMOSVS' },
            { id: 'F40', text: '[OFF]RONTINI' },
            { id: 'F41', text: 'OFFRONTINI' },
            { id: 'F42', text: 'OFFR.NTNI' },
            { id: 'F43', text: 'OFFRONTINI' },
            { id: 'F44', text: 'OFFRONTIN' },
            { id: 'F45', text: 'OFFRONTIN' },
            { id: 'F46', text: 'O<F>FRON<II>' },
            { id: 'F47', text: 'OFFRONII' },
            { id: 'F48', text: '[O]FRONTI' },
            { id: 'F49', text: 'OFFRON' },
            { id: 'F50', text: 'OFRONTI' },
            { id: 'F51', text: 'OFR.N' },
            { id: 'F52', text: 'FRONTI' },
            { id: 'F53', text: '[F]RON' },
            { id: 'F54', text: 'FRONTOF' },
            { id: 'F55', text: 'FRONTO' },
            { id: 'F56', text: 'FVSCI' },
            { id: 'F57', text: 'OFFVSCI' },
            { id: 'F58', text: '[OF].FVSC' },
            { id: 'F59', text: 'OF.FVS' },
            { id: 'F60', text: 'FVSCI' },
            { id: 'F61', text: 'FVSCI' },
            { id: 'F62', text: 'FVSCI' },
            { id: 'F63', text: 'F[VSC]I' },
            { id: 'F64', text: 'FVSCI' },
            { id: 'F65', text: 'FVSCI' },
            { id: 'F66', text: 'FVSCI' },
            { id: 'F67', text: 'FVS[CI]' },
            { id: 'F68', text: 'FVSC' },
            { id: 'F69', text: 'FVSC' },
            { id: 'G1', text: 'GALBINIM' },
            { id: 'G2', text: 'OFGALIC' },
            { id: 'G3', text: '[G]ALLICANI.MA' },
            { id: 'G4', text: 'GALLICA.MA' },
            { id: 'G5', text: 'GALI[ICANI]' },
            { id: 'G6', text: 'ALL[IC]AN' },
            { id: 'G7', text: 'GALLI.MANVS' },
            { id: 'G8', text: 'GALLIMA' },
            { id: 'G9', text: 'GALLI' },
            { id: 'G10', text: 'GEMINV' },
            { id: 'G11', text: 'OFGEM.MAE' },
            { id: 'G12', text: 'CLGEMMA' },
            { id: 'G13', text: 'GEMAE' },
            { id: 'G14', text: 'C.GEMM' },
            { id: 'G15', text: 'GENALISF' },
            { id: 'G16', text: '[O]FGERMA' },
            { id: 'G17', text: '<GER>MANIOF' },
            { id: 'G18', text: 'GERMANIOI' },
            { id: 'G19', text: 'GERMANIOI' },
            { id: 'G20', text: 'GERMNI<OF>' },
            { id: 'G21', text: 'GERMANI.FI' },
            { id: 'G22', text: '[GER]MANI<.F>' },
            { id: 'G23', text: 'GERF' },
            { id: 'G24', text: 'G.ERMANI' },
            { id: 'G25', text: 'GERMANI' },
            { id: 'G26', text: 'GERMA[NI]' },
            { id: 'G27', text: 'GER[MNI]' },
            { id: 'G28', text: 'CERMAIN' },
            { id: 'G29', text: 'GERMANI' },
            { id: 'G30', text: 'CERMAN' },
            { id: 'G31', text: 'GERMA<N>' },
            { id: 'G32', text: 'CERMAN' },
            { id: 'G33', text: '[G]ERMAN' },
            { id: 'G34', text: 'GERMA' },
            { id: 'G35', text: 'GERMA' },
            { id: 'G36', text: 'OIIGER' },
            { id: 'G37', text: 'OFFLAVI.GER.' },
            { id: 'G38', text: '<O>FFLAGER.' },
            { id: 'G39', text: 'OF.FL.GER.' },
            { id: 'G40', text: 'OFFL.CER' },
            { id: 'G41', text: 'OFFLGER' },
            { id: 'G42', text: 'OFFLGER' },
            { id: 'G43', text: 'OF.F.GE[R.]' },
            { id: 'G44', text: 'OFFGER' },
            { id: 'G45', text: 'OFFCER' },
            { id: 'G46', text: 'OFFGER.' },
            { id: 'G47', text: 'OFFC.ER' },
            { id: 'G48', text: 'OFFGER' },
            { id: 'G49', text: 'OFFCER' },
            { id: 'G50', text: 'OFFCEK' },
            { id: 'G51', text: 'OFFCE' },
            { id: 'H1', text: 'Q.IVL.HABI' },
            { id: 'I1', text: '<O>FFIC.INGEN' },
            { id: 'I2', text: 'OF.INGEN' },
            { id: 'I3', text: 'OF.INGEN' },
            { id: 'I4', text: 'OFINC.I' },
            { id: 'I5', text: 'OFINC.I' },
            { id: 'I6', text: 'OFINC' },
            { id: 'I7', text: 'INGENVI.F' },
            { id: 'I8', text: '[IN]GENVI' },
            { id: 'I9', text: 'INGENVI' },
            { id: 'I9*', text: '<I>NGEN<VI>' },
            { id: 'I9**', text: '<I>NGE<NVI>' },
            { id: 'I10', text: 'OFIVCVNDI' },
            { id: 'I11', text: 'OFIVCVNDI' },
            { id: 'I12', text: 'OF.[IV]CVN' },
            { id: 'I13', text: 'OF.IVCVN' },
            { id: 'I14', text: 'OF.IVCVN' },
            { id: 'I15', text: 'OF.IVCVN' },
            { id: 'I16', text: 'OF.IVCVN' },
            { id: 'I17', text: 'IVCVNDVS' },
            { id: 'I18', text: '[I]VCVNDV' },
            { id: 'I19', text: 'IVCVND[I]' },
            { id: 'I20', text: 'IVC.VND' },
            { id: 'I21', text: '[I]VCVND' },
            { id: 'I22', text: 'IVCVND' },
            { id: 'I23', text: 'OFCO.IV<C>' },
            { id: 'I24', text: 'OF.COIV' },
            { id: 'I25', text: 'FCO.IV' },
            { id: 'I26', text: 'ICOIV' },
            { id: 'I27', text: 'SEX.IVL.IVCVND' },
            { id: 'I28', text: 'OFIC.IVLI' },
            { id: 'I29', text: ':OFIVI:' },
            { id: 'I30', text: 'IVLI.' },
            { id: 'I31', text: 'IVLLINI' },
            { id: 'I32', text: 'IVLLINI' },
            { id: 'I33', text: 'IVLLINI' },
            { id: 'I34', text: 'IVLLIN' },
            { id: 'I35', text: 'IVLLN' },
            { id: 'I36', text: 'IVNII[I]' },
            { id: 'I37', text: 'IVNII' },
            { id: 'I38', text: 'I.VN' },
            { id: 'I39', text: 'OFIVSTI' },
            { id: 'I40', text: 'OFI.VST' },
            { id: 'I41', text: 'OF.IVS.' },
            { id: 'I42', text: 'IVSTI.OF' },
            { id: 'I43', text: 'IVSTI.OF' },
            { id: 'I44', text: 'IVSTID' },
            { id: 'I45', text: 'IVSTI' },
            { id: 'I46', text: '<I>VENALISMA' },
            { id: 'L1', text: 'OF.LABIONIS' },
            { id: 'L2', text: 'OF.L[ABIO]' },
            { id: 'L3', text: 'OF.LABE' },
            { id: 'L3*', text: 'OF.LAB<E>' },
            { id: 'L3**', text: 'OF.LAB<E>' },
            { id: 'L4', text: '=.LAB' },
            { id: 'L5', text: 'LABIO' },
            { id: 'L6', text: 'LARTIVS.' },
            { id: 'L7', text: 'LAVRATVS' },
            { id: 'L8', text: 'LAVR.I:O' },
            { id: 'L9', text: 'LEGITVM.O' },
            { id: 'L10', text: 'LENTVF' },
            { id: 'L11', text: 'OFL.IIPI' },
            { id: 'L12', text: 'LIBERTVS' },
            { id: 'L13', text: '<L>IBERTVS' },
            { id: 'L14', text: 'OFLICIN' },
            { id: 'L15', text: 'OFLICN' },
            { id: 'L16', text: 'LICINIANAO' },
            { id: 'L17', text: 'LICINIANAO' },
            { id: 'L18', text: '<L>IC.INIANA<O>' },
            { id: 'L19', text: '<L>CNIANA<O>' },
            { id: 'L20', text: 'LICINVS' },
            { id: 'L21', text: 'L.ICN.VS' },
            { id: 'L22', text: 'LIC.IA' },
            { id: 'L23', text: 'LOGIRNM' },
            { id: 'L24', text: 'LOCIRNVS' },
            { id: 'L25', text: 'LOGIRNI' },
            { id: 'L26', text: '<L>OGIRN' },
            { id: 'L27', text: 'LORI.R' },
            { id: 'L28', text: 'OF.LVCCEI' },
            { id: 'L29', text: 'OF.LVCCEI' },
            { id: 'L30', text: 'OFLVCCEI' },
            { id: 'L31', text: 'OF.LVCCE' },
            { id: 'L32', text: 'OF.LVCC' },
            { id: 'L33', text: 'OF.LVCC' },
            { id: 'L34', text: 'LVC[IVS]' },
            { id: 'L34*', text: 'LVCIVS' },
            { id: 'L35', text: 'LVPERCV.FE' },
            { id: 'L36', text: 'LVPP[A.F]' },
            { id: 'L37', text: 'LVPIMA' },
            { id: 'L38', text: 'LVPVS' },
            { id: 'M1', text: 'OFICMACCAR[I]' },
            { id: 'M2', text: 'OFI.MACCA' },
            { id: 'M3', text: 'OF.MACCAR' },
            { id: 'M4', text: 'OF.MACC[AR]' },
            { id: 'M4*', text: '<O>F.MACCA<R>' },
            { id: 'M5', text: 'OF.MACCAR' },
            { id: 'M7', text: 'OF.MACA' },
            { id: 'M8', text: 'MACCARI' },
            { id: 'M9', text: 'MACCARI' },
            { id: 'M10', text: 'MACCA' },
            { id: 'M11', text: 'MACA' },
            { id: 'M12', text: 'MAC' },
            { id: 'M13', text: 'MAC.RI.MAN' },
            { id: 'M14', text: 'MA.AC.II.R' },
            { id: 'M15', text: 'MAC[ER]' },
            { id: 'M16', text: 'MACIR' },
            { id: 'M17', text: 'MACRIN' },
            { id: 'M18', text: 'MAG[N]IMA' },
            { id: 'M19', text: 'MANDVILMA' },
            { id: 'M20', text: 'MANDOF' },
            { id: 'M21', text: '[MAN]DV.' },
            { id: 'M22', text: 'OFMANSVE' },
            { id: 'M23', text: 'OFMASV' },
            { id: 'M24', text: 'MAPONI' },
            { id: 'M25', text: 'MARINVS.FE' },
            { id: 'M26', text: 'MARINI' },
            { id: 'M27', text: 'MARINI' },
            { id: 'M28', text: '[MA]RSI' },
            { id: 'M29', text: 'MARS' },
            { id: 'M30', text: 'MARS' },
            { id: 'M31', text: 'MARTIA[LISFE]' },
            { id: 'M32', text: 'MARTIALIS.VA' },
            { id: 'M33', text: 'OFMASCLIN' },
            { id: 'M34', text: 'MSCLINI' },
            { id: 'M35', text: '[OF.]MASCLI' },
            { id: 'M36', text: 'OFMASC[L]' },
            { id: 'M37', text: 'OFMASO' },
            { id: 'M38', text: 'OFMASCI' },
            { id: 'M39', text: 'MASCLVS[.FE]' },
            { id: 'M40', text: 'MASCVLVS' },
            { id: 'M41', text: 'MASCLVS' },
            { id: 'M42', text: 'MASCVL<I>' },
            { id: 'M43', text: 'MASCLI' },
            { id: 'M44', text: 'MASCLI' },
            { id: 'M45', text: 'MASCL' },
            { id: 'M46', text: 'MASCL' },
            { id: 'M47', text: 'MASCLI.BAL BVS' },
            { id: 'M48', text: 'OFMASC[VL]' },
            { id: 'M49', text: 'OFMASCVL' },
            { id: 'M50', text: 'OFMASCL' },
            { id: 'M51', text: '<OF>MASCL' },
            { id: 'M52', text: 'OFMASC.' },
            { id: 'M53', text: 'OFMASC' },
            { id: 'M54', text: 'OFMAS' },
            { id: 'M55', text: 'OFMATE' },
            { id: 'M56', text: 'OF.MAT.VGE' },
            { id: 'M57', text: 'OFMATV' },
            { id: 'M58', text: 'MEOILLVS' },
        ];
